INSERT INTO CLIENT
VALUES (1,'paps',2,19);
INSERT INTO CLIENT
VALUES (2,'pops',2,19);
INSERT INTO CLIENT
VALUES (3,'pips',2,19);
INSERT INTO CLIENT
VALUES (4,'peps',2,19);
INSERT INTO CLIENT
VALUES (5,'poups',2,19);
INSERT INTO CLIENT
VALUES (6,'plips',2,19);
INSERT INTO CLIENT
VALUES (7,'plops',2,19);
INSERT INTO CLIENT
VALUES (8,'plaps',2,19);
INSERT INTO CLIENT
VALUES (9,'papis',2,19);
INSERT INTO CLIENT
VALUES (10,'takis',1,19);
INSERT INTO CLIENT
VALUES (11,'marios',0,19);
INSERT INTO CLIENT
VALUES (12,'takis',9,19);
INSERT INTO CLIENT
VALUES (13,'panagiotis',1,19);
INSERT INTO CLIENT
VALUES (14,'panagiotis',5,19);